version: "3.7"
services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - groceryshoppingmysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/qpassessment?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - groceryshoppingmysql-net
    environment:
      MYSQL_DATABASE: qpassessment
      MYSQL_USER: ashwin
      MYSQL_PASSWORD: Ashwin
      MYSQL_ROOT_PASSWORD: RAshwin
networks:
  groceryshoppingmysql-net:
